authapp/urls.py
from django.urls import re_path,path

from . import views
app_name='authapp'
urlpatterns = [
    path('accounts/profile/',views.profile_redirector,name='user_profile'),
    path('accounts/profile/update/',views.UserProfileUpdateView.as_view(),name='user_profile_update'),
    re_path(r'^@(?P<username>[\w-]+)/$', views.UserProfileView.as_view(), name='profile'),
]

bookbugs/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': 
        settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': 
        settings.STATIC_ROOT}),
    path('',include('authapp.urls',namespace='authapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authapp/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from smartfields import fields
from smartfields.dependencies import FileDependency
from smartfields.processors import ImageProcessor
import uuid
import os

# Create your models here.

#For renaming and saving user profile images in media_url
def rename_path_and_avatar(path):
        def wrapper(instance,filename):
            #avatar = filename.split('.')[0]
            ext = filename.split('.')[-1]
            if instance.pk:
                avatar_id = 'uid_%s'%(instance.pk)
                avatar_name = '%s_%s'%(instance.user.first_name, instance.user.last_name)
                filename = '{}_{}_{}.{}'.format(avatar_id,avatar_name,uuid.uuid4().hex,ext)
            else:
                random_id = 'r_id%s'%(uuid.uuid4().hex)
                filename = '{}_{}'.format(random_id,filename)
            return os.path.join(path,filename)
        return wrapper
avatar_image_upload_path = rename_path_and_avatar('user_avatar/')
# assign it `__qualname__`
avatar_image_upload_path.__qualname__ = 'avatar_image_upload_path'


class UserProfile(models.Model):

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='profile',on_delete=models.CASCADE)
    avatar = fields.ImageField(upload_to=avatar_image_upload_path,blank=True,default = 'static/user-bg.jpg', dependencies=[
        FileDependency( processor=ImageProcessor(
            format='JPEG', scale={'max_width': 150, 'max_height': 150})),
    ])
    twitter_url = models.URLField(_('Twitter'),max_length=50,null=True)

    
    about = models.TextField(blank=True)
   # user_type = models.CharField(max_length=1, choices=USER_TYPES, default='b')

    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if self.id and self.avatar:
            current_avatar = UserProfile.objects.get(pk=self.id).avatar
            if current_avatar != self.avatar:
                current_avatar.delete()
        super(UserProfile, self).save(*args, **kwargs)

    def get_absolute_url(self):
        target = reverse('authapp:profile', args=[self.user.username])
        return target

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

authapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from allauth.account import forms as allauth_forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from crispy_forms.bootstrap import StrictButton
from .models import UserProfile

#Start forms from here.

class UserForm(forms.ModelForm):
    class Meta(object):
        model = get_user_model()
        fields = ['first_name', 'last_name','email']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['last_name'].required = True
        self.fields['first_name'].required = True
        self.fields['email'].required = True
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout('first_name', 'last_name','email')


class UserProfileForm(forms.ModelForm):

    class Meta(object):
        model = UserProfile
        fields = ['about', 'avatar']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].required = False
        self.fields['avatar'].label = ''
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('about', css_class='materialize-textarea'),
            Field('avatar')
        )


class CustomLoginForm(allauth_forms.LoginForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.PasswordInput()
        self.helper = FormHelper(self)
        self.helper.col_class = True
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = field
           # del self.fields[field].widget.attrs['placeholder']
        self.helper.layout = Layout(
            'login', 'password', 'remember',
            StrictButton(
                'Sign In', type='submit', style='margin-top: 10px',
                css_class="waves-effect btn-large black waves-light btn right"),
        )

    
class CustomChangePwdForm(allauth_forms.ChangePasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomChangePwdForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = None
            del self.fields[field].widget.attrs['placeholder']

        self.helper.layout = Layout(
            'oldpassword', 'password1', 'password2',
            StrictButton(
                'Change Password', type='submit', name='action',
                css_class="waves-effect btn-large black waves-light btn right")
        )


class CustomAddEmailForm(allauth_forms.AddEmailForm):
    def __init__(self, *args, **kwargs):
        super(CustomAddEmailForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        self.fields['email'].widget.attrs['placeholder'] = None
        self.fields['email'].label = 'Email Address'

        del self.fields['email'].widget.attrs['placeholder']

        self.helper.layout = Layout(
            'email',
            StrictButton(
                'Add Email', name='action_add', type='submit',
                css_class="waves-effect btn-large black waves-light btn right")  # noqa
        )

    
class CustomResetPwdForm(allauth_forms.ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomResetPwdForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        del self.fields['email'].widget.attrs['placeholder']
        self.fields['email'].label = "Email Address"

        self.helper.layout = Layout(
            'email',
            StrictButton(
                'Reset My Password', type='submit',
                css_class="waves-effect btn-large black waves-light btn right"),
        )


class CustomResetPasswordKeyForm(allauth_forms.ResetPasswordKeyForm):
    def __init__(self, *args, **kwargs):
        super(CustomResetPasswordKeyForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True
        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = None
            del self.fields[field].widget.attrs['placeholder']

        self.helper.layout = Layout(
            'password1', 'password2',
            StrictButton(
                'Change Password', type='submit',
                css_class="waves-effect btn-large black waves-light btn right"),
        )

authapp/views.py
import uuid

from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.db.models import Prefetch
from .forms import UserForm, UserProfileForm
from .models import UserProfile

# Create your views here.
class UserProfileView(DetailView):
    template_name = 'authapp/user_profile.html'
    model = UserProfile
    context_object_name = 'profile'
    slug_url_kwarg = 'username'
    slug_field = 'user__username'


@login_required
def profile_redirector(request):
    return redirect('authapp:profile', username=request.user.username)


class UserProfileUpdateView(UpdateView):
    template_name = 'authapp/edit_profile.html'
    form_class = UserForm
    form_class_2 = UserProfileForm

    def get_context_data(self, **kwargs):
        context = super(UserProfileUpdateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(instance=self.request.user)
        if 'form2' not in context:
            context['form2'] = self.form_class_2(instance=self.request.user.profile)  # noqa
        return context

    def get(self, request, *args, **kwargs):
        super(UserProfileUpdateView, self).get(request, *args, **kwargs)
        self.object = self.get_object()
        form = self.form_class(instance=self.request.user)
        form2 = self.form_class_2(instance=self.request.user.profile)

        return self.render_to_response(self.get_context_data(
            form=form, form2=form2
        ))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST, instance=self.request.user)
        form2 = self.form_class_2(request.POST, request.FILES,
                                  instance=self.request.user.profile)

        if form.is_valid() and form2.is_valid():
            form.save()
            data = form2.save(commit=False)
            if request.FILES.get('avatar', None):
                data.avatar = request.FILES['avatar']
                data.avatar.name = '{0}_p.jpg'.format(str(uuid.uuid4()))
            data.save()
            return redirect('authapp:user_profile')
        else:
            return self.render_to_response(
                self.get_context_data(form=form, form2=form2)
                )

    def get_object(self, queryset=None):
        return self.request.user

templates/authapp/_user_profile_header.html
{% load static %}
{%load socialaccount%}
<div id="profile-page-header" class="card" style="margin:0px">
  <div class="card-image" style="overflow:hidden;">
      <img class="" src="{% static 'images/user-profile-bg.jpg' %}" alt="user background">
  </div>
  <figure class="card-profile-image">
      <img
      {% if user.profile.avatar %}
      src="{{ profile.avatar.url }}"
      
      {% else %}
      src="{% static 'images/user-profile-default.jpg' %}"
      {% endif %}
      alt="profile image" class="circle z-depth-2 responsive-img">
  </figure>
  <div class="card-content" id="profile-userdetails">
    <div class="row">
      <div class="col s3 offset-s2">
          <h4 class="card-title grey-text text-darken-4">{{ profile.user.first_name }} {{ profile.user.last_name }}</h4>
          <p class="medium-small grey-text">@{{ profile.user.username }}</p>
      </div>
      <div class="col s1 center-align">
          <a href="#" title="Posts">
          <h4 class="card-title grey-text text-darken-4">{{ profile.user.posts.count }}</h4>
          <p class="medium-small grey-text"><i class="material-icons">library_books</i></p>
        </a>
      </div>
      {% if request.user.id == profile.user.id %}
        <div class="col s1 right-align" style="margin-top:-5px">
          <a class="btn-floating waves-effect waves-light darken-1 right"
              data-tooltip="Edit profile" href="{% url 'authapp:user_profile_update' %}">
              <i class="material-icons">mode_edit</i>
          </a>
        </div>
      {% endif %}
    </div>
  </div>
</div>

templates/authapp/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Edit profile{% endblock %}

{% block content %}
  <h3 class="center">Update Profile</h3>
  <div class="container user-page-container">
    <div class="card-panel z-depth-0">
        <form method="post" enctype="multipart/form-data" id="profileEditForm">
            {% csrf_token %}
            {% crispy form %}
            {% crispy form2 %}
            <button type="submit" value="Update Profile" class="btn btn-large grey accent-2 darken-2 right waves-effect waves-light">Update Profile</button>
        </form>
    </div>
  </div>
{% endblock %}

templates/authapp/user_comments.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}{{ profile.user.username }}'s comments{% endblock %}
{% block content %}

  {% include "authapp/_user_profile_header.html" %}
  <div class="container">
    <h4 class="light header">Comments</h4>
    {% for comment in comments %}
      <div class="card">
        <div class="card-content">
          <a href="{{ comment.post.get_absolute_url }}">
            <span title="{{ post.title }}" class="card-title truncate">
              {{ comment.post.title }}
            </span>
          </a>
          <p>{{ comment.comment }}</p>
        </div>
        <div class="card-action">
          <a href="{{ comment.get_absolute_url }}">View on posts page.</a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/authapp/user_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}{{ profile.user.username }}'s profile{% endblock %}
{% block content %}

  {% include "authapp/_user_profile_header.html" %}

<div id="profile-page-about" class="center flow-text">
  <!-- start Profile About  -->
  <div class="card" style="border-radius: 7px;">
    <div class="card-content">
      <span class="card-title">About @{{ profile.user.username }}</span>
      {% if profile.about %}
        <p class="grey-text">{{ profile.about }}</p>
      {% else %}
      <p class="grey-text">Apparently, this user prefers to keep an air of mystery about them</p>
      {% endif %}
    </div>
  </div>
  <!-- end Profile About  -->
</div>

  
  
  
{% endblock %}