authapp/urls.py
from django.urls import re_path,path

from . import views
app_name='authapp'
urlpatterns = [
    path('accounts/profile/',views.profile_redirector,name='user_profile'),
    path('accounts/profile/update/',views.UserProfileUpdateView.as_view(),name='user_profile_update'),
    re_path(r'^@(?P<username>[\w-]+)/$', views.UserProfileView.as_view(), name='profile'),
]

bookbugs/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': 
        settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': 
        settings.STATIC_ROOT}),
    path('',include('authapp.urls',namespace='authapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/_footer.html
<footer class="page-footer grey darken-4 accent-2">
    <div class="container">
      <div class="row">
        <div class="col l4 s12" style="padding-right:20px ;">
          <h5 class="white-text center">About</h5>
          <p class="grey-text text-lighten-4 center">
            This project is part of qwikpik internship assignment.
            <br/>
            It was written by <a href="https://www.github.com/v1k45/" title="Vikas Yadav" class="white-text">v1k45</p>
        </div>
        <div class="col l4 s12">
          <div class="row">
            <div class="col l6 s12">
              <div class="container center" style="margin-top: 30%;">
                <a href="#" style="color: azure;"><span class="material-icons" style="font-size:48px;">
                  free_breakfast
                  </span></a>
              </div>
            </div>
            <div class="col l6 s12" style="padding-left: 40px;">
              <div class="container center" style="margin-top: 35%;">
                <a href="#" style="color: azure;"><span class="material-icons" style="font-size:48px;">
                  code
                  </span></a>
              </div>
            </div>
          </div>
        </div>
        <div class="col l4 s12" style="padding-left: 0px;">
          <h5 class="white-text center"><a href="/" style="color: azure;">blogghar</a></h5>
          <ul class="center">
            <li><a href="#" style="color: azure;">Home</a></li>
            <li><a href="#" style="color: azure;">Blog</a></li>
            <li><a href="#" style="color: azure;">Review</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright grey darken-3">
      <div class="container center">
      Made with &lt;3 using <a class="white-text" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>
  

templates/_navbar.html
{% load static %}
<div class="navbar-fixed">
  <nav role="navigation" class="grey accent-2 darken-4">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo"><img src="{% static 'images/nav-logo.png' %}" alt="Blogghar" style="height:60px;width: 150;"></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'authapp:user_profile' %}" class="dropdown-button"
              data-activates="user-dropdown" data-beloworigin="true" data-constrainwidth="false">
              <span>Welcome {{user.username}}</span> 
              <!--<img {% if user.profile.avatar %}
              src="{{ user.profile.avatar.url }}"
              {% else %}
              src="{% static 'images/user-profile-default.jpg' %}"
              {% endif %}class="profile-image right" style="width:40px;height: 40px;border-radius: 50%;" alt="">
          -->
            </a>
              <!-- user dropdown -->
              <ul id="user-dropdown" class="dropdown-content">
                <li>
                  <a href="{% url 'authapp:user_profile' %}">View profile</a>
                </li>
                <li>
                  <a href="{% url 'account_change_password' %}">Change pasword</a>
                </li>
                <li class="divider"></li>
                <li>
                  <a href="{% url 'account_logout' %}">Log out</a>
                </li>
              </ul>
          </li>
        {% else %}
          <li><a href="{% url 'account_login' %}">Login</a></li>
          <li><a href="{% url 'account_signup' %}" class="btn white black-text waves-effect default">Sign Up</a></li>
        {% endif %}
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block head_title %}{% endblock %} | blogghar</title>
    <!-- Compiled and minified CSS -->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {# block to easily inject any content in head #}
    {% block extra_head %}
    {% endblock %}
    <style type="text/css">
      .btn{
        border-radius: 7px;
      }
      form{
        border-radius: 15px;
      }
      </style>
  </head>
  <body>
    <header>
    {# include navbar #}
    {% include "_navbar.html" %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>


    {# include footer #}
    {% include "_footer.html" %}
    <!-- start javascript inclusions -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script type="text/javascript" src="{% static 'css/csrf.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".dropdown-button").dropdown();
    });
    </script>

<!-- alerts -->
    {% if messages %}
        <script type="text/javascript">
            $(document).ready(function () {
                {% for message in messages %}
                    Materialize.toast('{{ message }}', 5000, '{{ message.tags }}');
                {% endfor %}
            });
        </script>
    {% endif %}
<!-- end alerts -->

{# block to easily inject any javascript content #}
{% block extra_scripts %}
{% endblock %}
<!-- end javascript inclusions -->
</body>
</html>